spring:
  application:
    name:
      food-log
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: '20'
      minimumIdle: '10'
      idleTimeout: '60000'
      maxLifetime: '1800000'
      connectionTimeout: '30000'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  sql:
    init:
      mode: always
      schema-locations: 'classpath:schema.sql'
server:
  compression:
    enabled: true
swagger:
  base-url: "http://localhost:8080"

---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://api-postgres-db:5432/postgres
    username: ${POSTGRES_API_USER}
    password: ${POSTGRES_API_PASSWORD}
swagger:
  base-url: "https://api.casa.full4media.com"